### ISSUE TITLE
Leaking intent receiver

### ISSUE THREAD

**Issue by mehmetf** [domokit/sky_sdk#23] opened 2015-05-18 18:29 UTC
From logcat:

```
05-18 13:55:41.176: E/ActivityThread(13923): android.app.IntentReceiverLeaked: Activity org.domokit.sky.demo.SkyDemoActivity has leaked IntentReceiver org.domokit.sky.shell.TracingController$TracingBroadcastReceiver@7aef0e2 that was originally registered here. Are you missing a call to unregisterReceiver()?
05-18 13:55:41.176: E/ActivityThread(13923): 	at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:903)
05-18 13:55:41.176: E/ActivityThread(13923): 	at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:704)
05-18 13:55:41.176: E/ActivityThread(13923): 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1643)
05-18 13:55:41.176: E/ActivityThread(13923): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1623)
05-18 13:55:41.176: E/ActivityThread(13923): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1617)
05-18 13:55:41.176: E/ActivityThread(13923): 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:489)
05-18 13:55:41.176: E/ActivityThread(13923): 	at org.domokit.sky.shell.TracingController.<init>(TracingController.java:40)
05-18 13:55:41.176: E/ActivityThread(13923): 	at org.domokit.sky.shell.SkyActivity.onCreate(SkyActivity.java:38)
05-18 13:55:41.176: E/ActivityThread(13923): 	at org.domokit.sky.demo.SkyDemoActivity.onCreate(SkyDemoActivity.java:22)
```

**Comment by eseidelGoogle** [comment] 2015-05-18 21:32
I've seen this, not investigated the cause yet.  @abarth @chinmaygarde @qsr

**Comment by abarth** [comment] 2015-06-06 19:55
Should be fixed ^^^

**Closed by abarth** 2015-06-06 19:55 UTC

**Comment by spierce7** [comment] 2015-06-07 06:10
I pulled master tonight and was getting this error when I run the widgets example.

```
 E  Activity org.domokit.sky.demo.SkyDemoActivity has leaked IntentReceiver org.domokit.sky.shell.TracingController$TracingBroadcastReceiver@3445720f that was originally registered
                             here. Are you missing a call to unregisterReceiver()?
                         E  android.app.IntentReceiverLeaked: Activity org.domokit.sky.demo.SkyDemoActivity has leaked IntentReceiver org.domokit.sky.shell.TracingController$TracingBroadcastReceiver@34457
                            20f that was originally registered here. Are you missing a call to unregisterReceiver()?
                         E      at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:960)
                         E      at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:761)
                         E      at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:2003)
                         E      at android.app.ContextImpl.registerReceiver(ContextImpl.java:1983)
                         E      at android.app.ContextImpl.registerReceiver(ContextImpl.java:1977)
                         E      at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:503)
                         E      at org.domokit.sky.shell.TracingController.<init>(TracingController.java:40)
                         E      at org.domokit.sky.shell.SkyActivity.onCreate(SkyActivity.java:38)
                         E      at org.domokit.sky.demo.SkyDemoActivity.onCreate(SkyDemoActivity.java:22)
                         E      at android.app.Activity.performCreate(Activity.java:6221)
                         E      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                         E      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2614)
                         E      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                         E      at android.app.ActivityThread.access$900(ActivityThread.java:172)
                         E      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
                         E      at android.os.Handler.dispatchMessage(Handler.java:102)
                         E      at android.os.Looper.loop(Looper.java:145)
                         E      at android.app.ActivityThread.main(ActivityThread.java:5835)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at java.lang.reflect.Method.invoke(Method.java:372)
                         E      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)
               chromium  E  [ERROR:dart_error.cc(20)] 'http://localhost:9888/widgets_app.dart': warning: line 20 pos 17: unbalanced '[' opens here
                         E        children: [
                         E                  ^
                         E  'http://localhost:9888/widgets_app.dart': error: line 45 pos 7: unbalanced ')'
                         E        );
```

**Comment by abarth** [comment] 2015-06-07 15:09
The issue is fixed in source (which is in the https://github.com/domokit/mojo repo).  We haven't published an updated version of the sky_sdk since the fix, but @eseidelGoogle is working on doing that.

**Comment by eseidelGoogle** [comment] 2015-06-08 19:28
I am seeing a crash on quit, likely related to my fix:

E/AndroidRuntime(10657): FATAL EXCEPTION: main
E/AndroidRuntime(10657): Process: org.domokit.sky.demo, PID: 10657
E/AndroidRuntime(10657): java.lang.RuntimeException: Unable to stop activity {org.domokit.sky.demo/org.domokit.sky.demo.SkyDemoActivity}: java.lang.IllegalArgumentException: Receiver not registered: org.domokit.sky.shell.TracingController$TracingBroadcastReceiver@cbb412a
E/AndroidRuntime(10657): 	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3370)
E/AndroidRuntime(10657): 	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3416)
E/AndroidRuntime(10657): 	at android.app.ActivityThread.access$1100(ActivityThread.java:151)
E/AndroidRuntime(10657): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1325)
E/AndroidRuntime(10657): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(10657): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(10657): 	at android.app.ActivityThread.main(ActivityThread.java:5245)
E/AndroidRuntime(10657): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10657): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(10657): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime(10657): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
E/AndroidRuntime(10657): Caused by: java.lang.IllegalArgumentException: Receiver not registered: org.domokit.sky.shell.TracingController$TracingBroadcastReceiver@cbb412a
E/AndroidRuntime(10657): 	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:765)
E/AndroidRuntime(10657): 	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1666)
E/AndroidRuntime(10657): 	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:511)
E/AndroidRuntime(10657): 	at org.domokit.sky.shell.TracingController.stop(TracingController.java:43)
E/AndroidRuntime(10657): 	at org.domokit.sky.shell.SkyActivity.onStop(SkyActivity.java:47)
E/AndroidRuntime(10657): 	at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1277)
E/AndroidRuntime(10657): 	at android.app.Activity.performStop(Activity.java:6130)
E/AndroidRuntime(10657): 	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3367)
E/AndroidRuntime(10657): 	... 10 more
W/ActivityManager(  764):   Force finishing activity 1 org.domokit.sky.demo/.SkyDemoActivity
